// <auto-generated />
using System;
using CapstoneProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CapstoneProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181024183102_new table")]
    partial class newtable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CapstoneProject.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CapstoneProject.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupId");

                    b.Property<int?>("TravellerId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TravellerId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("CapstoneProject.Models.GroupTraveller", b =>
                {
                    b.Property<int>("GroupId");

                    b.Property<int>("TravellerId");

                    b.HasKey("GroupId", "TravellerId");

                    b.HasIndex("TravellerId");

                    b.ToTable("GroupTraveller");
                });

            modelBuilder.Entity("CapstoneProject.Models.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PubDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("CapstoneProject.Models.Traveller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Travellers");
                });

            modelBuilder.Entity("CapstoneProject.Models.TravellerJournal", b =>
                {
                    b.Property<int>("TravellerId");

                    b.Property<int>("JournalId");

                    b.HasKey("TravellerId", "JournalId");

                    b.HasIndex("JournalId");

                    b.ToTable("TravellerJournal");
                });

            modelBuilder.Entity("CapstoneProject.Models.GroupMember", b =>
                {
                    b.HasOne("CapstoneProject.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CapstoneProject.Models.Traveller", "Traveller")
                        .WithMany()
                        .HasForeignKey("TravellerId");
                });

            modelBuilder.Entity("CapstoneProject.Models.GroupTraveller", b =>
                {
                    b.HasOne("CapstoneProject.Models.Group", "Group")
                        .WithMany("GroupTravellers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CapstoneProject.Models.Traveller", "Traveller")
                        .WithMany("GroupTravellers")
                        .HasForeignKey("TravellerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CapstoneProject.Models.TravellerJournal", b =>
                {
                    b.HasOne("CapstoneProject.Models.Journal", "Journal")
                        .WithMany("TravellerJournals")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CapstoneProject.Models.Traveller", "Traveller")
                        .WithMany("TravellerJournals")
                        .HasForeignKey("TravellerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
